CREATE TABLE logs (
    id bigint PRIMARY KEY,
    clientmemberclass character varying(255),
    clientmembercode character varying(255),
    clientsubsystemcode character varying(255),
    clientxroadinstance character varying(255),
    messageprotocolversion character varying(255),
    producerdurationproducerview integer,
    representedpartyclass character varying(255),
    representedpartycode character varying(255),
    requestattachmentcount integer,
    requestindate date,
    requestints bigint,
    requestmimesize bigint,
    requestsoapsize bigint,
    responseattachmentcount integer,
    responsemimesize bigint,
    responsesoapsize bigint,
    securityservertype character varying(255),
    servicecode character varying(255),
    servicememberclass character varying(255),
    servicemembercode character varying(255),
    servicesubsystemcode character varying(255),
    serviceversion character varying(255),
    servicexroadinstance character varying(255),
    succeeded boolean,
    totalduration integer
);