"""
Django settings for interface project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import logging
import yaml
from logger_manager import setup_logger
from dateutil import relativedelta

# Open Data specific settings
# X-Road instances in Estonia: ee-dev, ee-test, EE
X_ROAD_INSTANCE = 'sample'
APPLICATION_DIR = '/srv/app'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Sample: ALLOWED_HOSTS = ['opmon-opendata', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'gui',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'interface.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'interface.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'database', 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Tallinn'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Ignore Django internal logging mechanisms
LOGGING = None

# Open Data specific settings

LOGS_DIR = '{0}/{1}/logs/'.format(APPLICATION_DIR, X_ROAD_INSTANCE)

LOG = {}

LOG['path'] = os.path.join(LOGS_DIR, 'log_opendata_interface_{0}.json'.format(X_ROAD_INSTANCE))
LOG['name'] = 'opendata_module - interface'
LOG['max_file_size'] = 2 * 1024 * 1024
LOG['backup_count'] = 10
LOG['level'] = logging.INFO

# Output heartbeat after every HEARTBEAT['interval'] seconds
HEARTBEAT = {
    'interval': 3600,
    'api_file': 'opendata-interface-api',
    'gui_file': 'opendata-interface-gui',
    'dir': '{0}/{1}/heartbeat'.format(APPLICATION_DIR, X_ROAD_INSTANCE)
}

setup_logger(logger_name='opendata-interface', log_level=LOG['level'],
             log_path=LOG['path'], max_file_size=LOG['max_file_size'],
             backup_count=LOG['backup_count'])

DISCLAIMER = """<p>X-Road monitoring data is collected from Estonian X-Road members security servers available
by X-Road Center (Republic of Estonia Information System Authority, Riigi Infosüsteemi Amet, RIA)
and published as opendata with a delay of 10 days from actual transaction execution time.</p>
<p>Data is renewed nightly, between 0:00-6:00 (EET UTC+2h / EEST UTC+3h).</p>
<p>Timestamps (specifically <em>requestInTs</em>) are rounded to hour precision and presented in form of Unix timstamp (epoch time).</p>
<p>According to Security Authorities Act [1] §5 the security authorities are the
Estonian Internal Security Service and the Estonian Foreign Intelligence Service. Their authorizations are described in
chapter 4 (§21 - 35) of the above mentioned act. Based on aspects stated in the State Secrets and
Classified Information of Foreign States Act [2] §11 section 3, §7 p 10 and § 8 p 1 and in the
Public Information Act [3] §35 section 1 p 1, 31, 51 the X-Road usage statistics of security authorities is
considered to be for internal use only. X-Road data that is being published as open data by RIA does not contain
information about the security authorities.</p>

<ul style="list-style-type: none;">
<li>[1] <a href="https://www.riigiteataja.ee/en/eli/ee/521062017015/consolide/current" target="_new">Security Authorities Act</a></li>
<li>[2] <a href="https://www.riigiteataja.ee/en/eli/ee/519062017007/consolide/current" target="_new">Foreign States Act</a></li>
<li>[3] <a href="https://www.riigiteataja.ee/en/eli/ee/518012016001/consolide/current" target="_new">Public Information Act</li>
</ul>
""".format(DAYS)

HEADER = """<table width="100%" align= "center" border= "0" cellpadding= "0" cellspacing= "0" style= "margin:0 auto">
<tbody>
<tr bgcolor= "#ffffff">
<td width="66%" align= "left">
<a href="https://www.ria.ee/en/">
<img src= "/static/gui/ria_100_en.png" alt= "Republic of Estonia Information System Authority"
style= "display:block; height:auto;" height= "auto" align="left" valign="top">
</a>
<a href="https://www.ria.ee/en/x-road.html">
<img src= "/static/gui/xroad_100_en.png" alt= "X-ROAD" style= "display:block; height:auto;" height= "auto" align="left" valign="top"></a>
</td>
<td width="33%" align= "right"><img src= "/static/gui/eu_rdf_100_en.png" alt= "European Union / European Regional Development Fund / Investing in your future"
style= "display:block; height:auto;" height= "auto" align="right" valign="top">
</td>
</tr>
</tbody>
</table>
"""

FOOTER = """<hr />
<p class="text-left" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;line-height:16px;color:#999">
<a href="https://github.com/ria-ee/X-Road-opmonitor/blob/master/docs/opendata/user_guide/ug_opendata_interface.md" target="_new" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;line-height:16px;color:#999">User Guide</a> |
<a href="https://github.com/ria-ee/X-Road-opmonitor/blob/master/docs/opendata/user_guide/ug_opendata_api.md" target="_new" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;line-height:16px;color:#999">API documentation</a> |
<a href="https://github.com/ria-ee/X-Road-opmonitor/blob/master/docs/opendata/user_guide/cfg_lists/field_data.yaml" target="_new" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;line-height:16px;color:#999">Fields</a></p>
<p class="text-left" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;line-height:16px;color:#999"><a href="https://www.ria.ee/en/contact.html" target_"new" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;line-height:16px;color:#999">Contact</a> |
<a href="mailto:help@ria.ee?subject=X-Road v6 usage statistics, Opendata" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;line-height:16px;color:#999">Helpdesk</a></p>
<hr />
<p class="text-left" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;line-height:12px;color:#999">The Opendata application was developed by <a target="_new" href="https://www.stacc.ee/" style="font-family:Roboto,Helvetica Neue,Helvetica,Arial,sans-serif;line-height:12px;color:#999">Tarkvara Tehnoloogia Arenduskeskus OÜ (STACC)</a></p>
"""

PREVIEW_LIMIT = 100

POSTGRES_CONFIG = {
    'host_address': '',
    'port': 5432,
    'database_name': 'opendata_{0}'.format(X_ROAD_INSTANCE.lower().replace('-', '_')),
    'table_name': 'logs',
    'user': 'interface_{0}'.format(X_ROAD_INSTANCE.lower().replace('-', '_')),
    'password': '${PWD_for_interface}'
}

FIELD_DATA_YAML = os.path.join(BASE_DIR, 'cfg_lists', 'field_data.yaml')
with open(FIELD_DATA_YAML) as field_data_file:
    FIELD_DESCRIPTIONS = yaml.safe_load(field_data_file)['fields']

IN_MAINTENANCE = False
